export interface Packaging {
  reg: number,
  part_number: string,
  part_weight: string,
  part_uom: string,
  part_length: string,
  part_width: string,
  part_height: string,
  unit_load_description: string,
  bc_per_unit_load: string,
  pieces_pallet: string,
  mixed_load: string,
  unit_load_length: string,
  unit_load_width: string,
  unit_load_heght1: string,
  unit_load_diameter: string,
  base_container_description: string,
  qty_base_container: string,
  base_container_length: string,
  base_container_width: string,
  base_container_height: string,
  base_container_diameter: string,
  vendor: string,
  is_editing?: boolean
}
